version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: x86
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  VCPKG_DEFAULT_TRIPLET: x86-windows-static
  BUILDCACHE_DIR: c:\tools\buildcache\cache
  BUILDCACHE_DEBUG: 1
install:
- cmd: >-
    cd C:\projects\Schiffbruch

    vcpkg version

    vcpkg update

    vcpkg upgrade --no-dry-run

    vcpkg install sfml:x86-windows-static

    vcpkg integrate install
cache:
- C:\Tools\vcpkg\installed\
- c:\tools\buildcache\cache
- C:\Tools\vcpkg\downloads\
- C:\Tools\vcpkg\packages\
- C:\Users\appveyor\AppData\Local\vcpkg\archives\
before_build:
- cmd: >-
    cd c:\projects\Schiffbruch

    git submodule update --init --recursive

    if not exist build mkdir build

    cd build

    cmake -DENABLE_IPO=True -DCMAKE_BUILD_TYPE=Release -DVC_STATIC=True -G "Visual Studio 16 2019" -A Win32 -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
build:
  project: build\Schiffbruch.vcxproj
  parallel: true
  verbosity: normal
after_build:
- cmd: >-
    cd C:\projects\Schiffbruch\build\Release

    7z a ..\..\Schiffbruch.zip Schiffbruch.exe

    echo %time%

artifacts:
- path: Schiffbruch.zip
deploy: off
