#pragma once

const unsigned int KXPIXEL = 54;		// Breite der Kacheln
const unsigned int KYPIXEL = 44;		// Hoehe der Kacheln
const unsigned int S1XPIXEL = 20;		// Breite der Schrift1
const unsigned int S1YPIXEL = 20;		// Höhe der Schrift1
const unsigned int S1ABSTAND = 13;		// Abstand zum nächsten Buchstaben
const unsigned int S2XPIXEL = 10;		// Breite der Schrift2
const unsigned int S2YPIXEL = 15;		// Höhe der Schrift2
const unsigned int S2ABSTAND = 10;		// Abstand zum nächsten Buchstaben
const unsigned int MAXXKACH = 60;		// Anzahl der Kacheln
const unsigned int MAXYKACH = 60;
const unsigned int MAXSCAPEX = 3360;	// Größe der Scapesurface
const unsigned int MAXSCAPEY = 1700;
const unsigned int MAXX = 800;			// Bildschirmauflösung
const unsigned int MAXY = 600;
const unsigned int GIPFEL = 3;			// Hoehe des Gipfels
const unsigned int MAXFLUSS = 1000;		// Maximale Flusslänge
const unsigned int FLUSSANZAHL = 1;		// Wieviele Flüsse? Mehr als 1 funktioniert seltsamerweise nicht mehr..
const unsigned int SKARTEX = 370;		// Schatzkartenbreite
const unsigned int SKARTEY = 370;		// Schatzkartenhöhe

const unsigned int MEERWELLEN = 0;
const unsigned int FLUSS1 = MEERWELLEN + 1;
const unsigned int FLUSS2 = MEERWELLEN + 2;
const unsigned int FLUSS3 = MEERWELLEN + 3;
const unsigned int FLUSS4 = MEERWELLEN + 4;
const unsigned int FLUSS5 = MEERWELLEN + 5;
const unsigned int FLUSS6 = MEERWELLEN + 6;
const unsigned int FLUSS7 = MEERWELLEN + 7;
const unsigned int FLUSS8 = MEERWELLEN + 8;
const unsigned int FLUSS9 = MEERWELLEN + 9;
const unsigned int FLUSS10 = MEERWELLEN + 10;
const unsigned int MUENDUNG1 = MEERWELLEN + 11;
const unsigned int MUENDUNG2 = MEERWELLEN + 12;
const unsigned int MUENDUNG3 = MEERWELLEN + 13;
const unsigned int MUENDUNG4 = MEERWELLEN + 14;
const unsigned int QUELLE1 = MEERWELLEN + 15;
const unsigned int QUELLE2 = MEERWELLEN + 16;	// Wenn hier was eingefügt wird, auch die FillRohr ändern!!
const unsigned int QUELLE3 = MEERWELLEN + 17;
const unsigned int QUELLE4 = MEERWELLEN + 18;
const unsigned int SCHLEUSE1 = MEERWELLEN + 19;
const unsigned int SCHLEUSE2 = MEERWELLEN + 20;
const unsigned int SCHLEUSE3 = MEERWELLEN + 21;
const unsigned int SCHLEUSE4 = MEERWELLEN + 22;
const unsigned int SCHLEUSE5 = MEERWELLEN + 23;
const unsigned int SCHLEUSE6 = MEERWELLEN + 24;
const unsigned int BAUM1 = 25;
const unsigned int BAUM2 = BAUM1 + 1;
const unsigned int BAUM3 = BAUM1 + 2;
const unsigned int BAUM4 = BAUM1 + 3;
const unsigned int BUSCH = BAUM1 + 4;
const unsigned int BAUM1DOWN = BAUM1 + 5;
const unsigned int BAUM2DOWN = BAUM1 + 6;
const unsigned int BAUM3DOWN = BAUM1 + 7;
const unsigned int BAUM4DOWN = BAUM1 + 8;
const unsigned int BAUMGROSS = BAUM1 + 9;
const unsigned int FEUER = BAUM1 + 10;
const unsigned int WRACK = BAUM1 + 11;
const unsigned int WRACK2 = BAUM1 + 12;
const unsigned int FELD = 38;
const unsigned int ZELT = FELD + 1;
const unsigned int BOOT = FELD + 2;
const unsigned int ROHR = FELD + 3;
const unsigned int SOS = FELD + 4;
const unsigned int HAUS1 = FELD + 5;
const unsigned int HAUS2 = FELD + 6;
const unsigned int HAUS3 = FELD + 7;
const unsigned int FEUERSTELLE = FELD + 8;
const unsigned int CUPFEIL = 47;
const unsigned int CURICHTUNG = CUPFEIL + 1;
const unsigned int CUUHR = CUPFEIL + 2;
const unsigned int GUYLINKS = 50;
const unsigned int GUYOBEN = GUYLINKS + 1;
const unsigned int GUYRECHTS = GUYLINKS + 2;
const unsigned int GUYUNTEN = GUYLINKS + 3;
const unsigned int GUYSUCHEN = GUYLINKS + 4;
const unsigned int GUYESSEN = GUYLINKS + 5;
const unsigned int GUYTRINKEN = GUYLINKS + 6;
const unsigned int GUYFAELLEN = GUYLINKS + 7;
const unsigned int GUYWARTEN = GUYLINKS + 8;
const unsigned int GUYFELD = GUYLINKS + 9;
const unsigned int GUYBINDENOBEN = GUYLINKS + 10;
const unsigned int GUYBINDENUNTEN = GUYLINKS + 11;
const unsigned int GUYSCHLAFEN = GUYLINKS + 12;
const unsigned int GUYSCHLAFZELT = GUYLINKS + 13;
const unsigned int GUYGEHINZELT = GUYLINKS + 14;
const unsigned int GUYHINLEGEN = GUYLINKS + 15;
const unsigned int GUYAUFSTEHEN = GUYLINKS + 16;
const unsigned int GUYANGELN1LINKS = GUYLINKS + 17;
const unsigned int GUYANGELN1OBEN = GUYLINKS + 18;
const unsigned int GUYANGELN1RECHTS = GUYLINKS + 19;
const unsigned int GUYANGELN1UNTEN = GUYLINKS + 20;
const unsigned int GUYANGELN2LINKS = GUYLINKS + 21;
const unsigned int GUYANGELN2OBEN = GUYLINKS + 22;
const unsigned int GUYANGELN2RECHTS = GUYLINKS + 23;
const unsigned int GUYANGELN2UNTEN = GUYLINKS + 24;
const unsigned int GUYANGELN3LINKS = GUYLINKS + 25;
const unsigned int GUYANGELN3OBEN = GUYLINKS + 26;
const unsigned int GUYANGELN3RECHTS = GUYLINKS + 27;
const unsigned int GUYANGELN3UNTEN = GUYLINKS + 28;
const unsigned int GUYSCHLAGEN = GUYLINKS + 29;
const unsigned int GUYBOOTLINKS = GUYLINKS + 30;
const unsigned int GUYBOOTOBEN = GUYLINKS + 31;
const unsigned int GUYBOOTRECHTS = GUYLINKS + 32;
const unsigned int GUYBOOTUNTEN = GUYLINKS + 33;
const unsigned int GUYBOOTANGELN1 = GUYLINKS + 34;
const unsigned int GUYBOOTANGELN2 = GUYLINKS + 35;
const unsigned int GUYBOOTANGELN3 = GUYLINKS + 36;
const unsigned int GUYTAUCHEN1 = GUYLINKS + 37;
const unsigned int GUYTAUCHEN2 = GUYLINKS + 38;
const unsigned int GUYTAUCHEN3 = GUYLINKS + 39;
const unsigned int GUYHAMMER = GUYLINKS + 40;
const unsigned int GUYKLETTERN1 = GUYLINKS + 41;
const unsigned int GUYKLETTERN2 = GUYLINKS + 42;
const unsigned int GUYHAMMER2 = GUYLINKS + 43;
const unsigned int GUYGEHINHAUS = GUYLINKS + 44;
const unsigned int GUYSCHLAFHAUS = GUYLINKS + 45;
const unsigned int GUYGEHAUSHAUS = GUYLINKS + 46;
const unsigned int GUYANZUENDEN = GUYLINKS + 47;
const unsigned int GUYAUSSCHAU = GUYLINKS + 48;
const unsigned int GUYSCHAUFELN = GUYLINKS + 49;
const unsigned int GUYSCHIFF = GUYLINKS + 50;
const unsigned int GUYSCHIFFDOWN = GUYLINKS + 51;
const unsigned int GUYSCHWIMMEN = GUYLINKS + 52;
const unsigned int GUYTOD = GUYLINKS + 53;
const unsigned int GUYBOOTTOD = GUYLINKS + 54;
const unsigned int GUYBOOTWARTEN = GUYLINKS + 55;
const unsigned int GUYSCHLEUDER = GUYLINKS + 56;
const unsigned int BUTTGITTER = 107;
const unsigned int BUTTANIMATION = BUTTGITTER + 1;
const unsigned int BUTTBEENDEN = BUTTGITTER + 2;
const unsigned int BUTTNEU = BUTTGITTER + 3;
const unsigned int BUTTTAGNEU = BUTTGITTER + 4;
const unsigned int BUTTSOUND = BUTTGITTER + 5;
const unsigned int BUTTAKTION = BUTTGITTER + 6;
const unsigned int BUTTBAUEN = BUTTGITTER + 7;
const unsigned int BUTTINVENTAR = BUTTGITTER + 8;
const unsigned int BUTTWEITER = BUTTGITTER + 9;
const unsigned int BUTTSTOP = BUTTGITTER + 10;
const unsigned int BUTTABLEGEN = BUTTGITTER + 11;
const unsigned int BUTTSUCHEN = 119;
const unsigned int BUTTESSEN = BUTTSUCHEN + 1;
const unsigned int BUTTSCHLAFEN = BUTTSUCHEN + 2;
const unsigned int BUTTFAELLEN = BUTTSUCHEN + 3;
const unsigned int BUTTANGELN = BUTTSUCHEN + 4;
const unsigned int BUTTANZUENDEN = BUTTSUCHEN + 5;
const unsigned int BUTTAUSSCHAU = BUTTSUCHEN + 6;
const unsigned int BUTTSCHATZKARTE = BUTTSUCHEN + 7;
const unsigned int BUTTSCHATZ = BUTTSUCHEN + 8;
const unsigned int BUTTSCHLEUDER = BUTTSUCHEN + 9;
const unsigned int BUTTZELT = 129;
const unsigned int BUTTFELD = BUTTZELT + 1;
const unsigned int BUTTBOOT = BUTTZELT + 2;
const unsigned int BUTTROHR = BUTTZELT + 3;
const unsigned int BUTTSOS = BUTTZELT + 4;
const unsigned int BUTTHAUS1 = BUTTZELT + 5;
const unsigned int BUTTHAUS2 = BUTTZELT + 6;
const unsigned int BUTTHAUS3 = BUTTZELT + 7;
const unsigned int BUTTFEUERST = BUTTZELT + 8;
const unsigned int BUTTFRAGEZ = BUTTZELT + 9;
const unsigned int BUTTDESTROY = BUTTZELT + 10;
const unsigned int SAEULE1 = 140;
const unsigned int SAEULE2 = SAEULE1 + 1;
const unsigned int SAEULE3 = SAEULE1 + 2;
const unsigned int ROHAST = 143;
const unsigned int ROHSTAMM = ROHAST + 1;
const unsigned int ROHSTEIN = ROHAST + 2;
const unsigned int ROHAXT = ROHAST + 3;
const unsigned int ROHBLATT = ROHAST + 4;
const unsigned int ROHEGGE = ROHAST + 5;
const unsigned int ROHLIANE = ROHAST + 6;
const unsigned int ROHANGEL = ROHAST + 7;
const unsigned int ROHHAMMER = ROHAST + 8;
const unsigned int ROHFERNROHR = ROHAST + 9;
const unsigned int ROHSTREICHHOLZ = ROHAST + 10;
const unsigned int ROHSCHAUFEL = ROHAST + 11;
const unsigned int ROHKARTE = ROHAST + 12;
const unsigned int ROHSCHLEUDER = ROHAST + 13;
const unsigned int ROEMISCH1 = 157;
const unsigned int ROEMISCH2 = ROEMISCH1 + 1;
const unsigned int INVPAPIER = 159;
const unsigned int RING = INVPAPIER + 1;
const unsigned int KREUZ = INVPAPIER + 2;
const unsigned int JA = INVPAPIER + 3;
const unsigned int NEIN = INVPAPIER + 4;
const unsigned int SONNE = INVPAPIER + 5;
const unsigned int PROGRAMMIERUNG = 165;
const unsigned int DIRKPLATE = PROGRAMMIERUNG + 1;
const unsigned int MATTHIAS = PROGRAMMIERUNG + 2;
const unsigned int TOBIAS = PROGRAMMIERUNG + 3;
const unsigned int SIGRID = PROGRAMMIERUNG + 4;
const unsigned int SOUNDS = PROGRAMMIERUNG + 5;
const unsigned int PATHFINDING = PROGRAMMIERUNG + 6;
const unsigned int JOHN = PROGRAMMIERUNG + 7;
const unsigned int HEIKO = PROGRAMMIERUNG + 8;
const unsigned int GISELA = PROGRAMMIERUNG + 9;
const unsigned int WEITEREHILFE = PROGRAMMIERUNG + 10;
const unsigned int TESTSPIELER = PROGRAMMIERUNG + 11;
const unsigned int SCHWARZ = PROGRAMMIERUNG + 12;
const unsigned int MUSIK = PROGRAMMIERUNG + 13;
const unsigned int DPSOFTWARE = PROGRAMMIERUNG + 14;
const unsigned int BILDANZ = DPSOFTWARE + 1; // Wieviele Bilder

// Sounds
const unsigned int WAVNICHTS = 0;
const unsigned int WAVSTURM = 1;
const unsigned int WAVSCHWIMMEN = WAVSTURM + 1;
const unsigned int WAVPLATSCH = WAVSTURM + 2;
const unsigned int WAVFAELLEN = WAVSTURM + 3;
const unsigned int WAVSCHLAGEN = WAVSTURM + 4;
const unsigned int WAVSCHLEUDER = WAVSTURM + 5;
const unsigned int WAVSCHAUFELN = WAVSTURM + 6;
const unsigned int WAVHAMMER = WAVSTURM + 7;
const unsigned int WAVCRASH = WAVSTURM + 8;
const unsigned int WAVSCHNARCHEN = WAVSTURM + 9;
const unsigned int WAVTRINKEN = WAVSTURM + 10;
const unsigned int WAVKNISTERN = WAVSTURM + 11;
const unsigned int WAVANGEL = WAVSTURM + 12;
const unsigned int WAVWALD = 14;
const unsigned int WAVFEUER = WAVWALD + 1;
const unsigned int WAVBRANDUNG = WAVWALD + 2;
const unsigned int WAVBAUMFAELLT = WAVWALD + 3;
const unsigned int WAVFLUSS = WAVWALD + 4;
const unsigned int WAVKLICK = 19;
const unsigned int WAVKLICK2 = WAVKLICK + 1;
const unsigned int WAVLOGO = WAVKLICK + 2;
const unsigned int WAVABSPANN = WAVKLICK + 3;
const unsigned int WAVWOLF = WAVKLICK + 4;
const unsigned int WAVERFINDUNG = WAVKLICK + 5;
const unsigned int WAVANZ = WAVERFINDUNG + 1;	// Anzahl der Sounds

// Menüs
const unsigned int MEKEINS = 0;
const unsigned int MEAKTION = 1;
const unsigned int MEBAUEN = 2;
const unsigned int MEINVENTAR = 3;

// Textfelder
const unsigned int TXTTEXTFELD = 0;
const unsigned int TXTFPS = 1;
const unsigned int TXTTAGESZEIT = 2;
const unsigned int TXTCHANCE = 3;
const unsigned int TXTPAPIER = 4;		// Muß!!! als letztes stehen
const unsigned int TEXTANZ = 5;			// Wieviele Textbreiche

// Resourcen
const unsigned int WASSER = 0;
const unsigned int NAHRUNG = 1;
const unsigned int GESUNDHEIT = 2;

// Spielzustände
const unsigned int SZNICHTS = 0;
const unsigned int SZINTRO = 1;
const unsigned int SZSPIEL = 2;
const unsigned int SZABSPANN = 3;
const unsigned int SZGERETTET = 4;
const unsigned int SZLOGO = 5;

// Bilder
static const char Misc[] = "MISC";
static const char Panel[] = "PANEL";
static const char GuyAni[] = "GUYANI";
static const char Animation[] = "ANIMATION";
static const char Schrift1[] = "SCHRIFT1";
static const char Schrift2[] = "SCHRIFT2";
static const char TextFeld[] = "TEXTFELD";
static const char Papier[] = "PAPIER";
static const char Baum[] = "BAUM";
static const char Cursorbmp[] = "CURSORBMP";
static const char Buttons[] = "BUTTONS";
static const char Inventarbmp[] = "INVENTARBMP";
static const char Bau[] = "BAU";
static const char Credits[] = "CREDITS";
static const char Logo[] = "LOGO";
