#pragma once

const int KXPIXEL = 54;              // Width of the tile
const int KYPIXEL = 44;              // Height of the tile
const unsigned int S1XPIXEL = 20;    // Width of the Schrift1
const unsigned int S1YPIXEL = 20;    // Height of the Schrift1
const unsigned int S1ABSTAND = 13;   // Distance to the next letter
const unsigned int S2XPIXEL = 10;    // Width of the Schrift2
const unsigned int S2YPIXEL = 15;    // Height of the Schrift2
const unsigned int S2ABSTAND = 10;   // Distance to the next letter
const unsigned int MAXXKACH = 60;    // Number of tiles
const unsigned int MAXYKACH = 60;
const unsigned int MAXSCAPEX = 3360; // Size of the scape surface
const unsigned int MAXSCAPEY = 1700;
const unsigned int MAXX = 1280;      // Display resolution
const unsigned int MAXY = 720;
const unsigned int GIPFEL = 3;       // Height of the summit
const unsigned int MAXFLUSS = 1000;  // Maximal river length
const unsigned int FLUSSANZAHL = 1;  // How many rivers? More than one somehow doesn't seem to work anymore...
const unsigned int SKARTEX = 370;    // Treasure map width
const unsigned int SKARTEY = 370;    // Treasure map height

enum Tiles
{
    Meerwellen = 0,
    Fluss1 = Meerwellen + 1,
    Fluss2 = Meerwellen + 2,
    Fluss3 = Meerwellen + 3,
    Fluss4 = Meerwellen + 4,
    Fluss5 = Meerwellen + 5,
    Fluss6 = Meerwellen + 6,
    Fluss7 = Meerwellen + 7,
    Fluss8 = Meerwellen + 8,
    Fluss9 = Meerwellen + 9,
    Fluss10 = Meerwellen + 10,
    Muendung1 = Meerwellen + 11,
    Muendung2 = Meerwellen + 12,
    Muendung3 = Meerwellen + 13,
    Muendung4 = Meerwellen + 14,
    Quelle1 = Meerwellen + 15,
    Quelle2 = Meerwellen + 16, // When inserting something here, also change FillRohr!!
    Quelle3 = Meerwellen + 17,
    Quelle4 = Meerwellen + 18,
    Schleuse1 = Meerwellen + 19,
    Schleuse2 = Meerwellen + 20,
    Schleuse3 = Meerwellen + 21,
    Schleuse4 = Meerwellen + 22,
    Schleuse5 = Meerwellen + 23,
    Schleuse6 = Meerwellen + 24,
    Baum1 = 25,
    Baum2 = Baum1 + 1,
    Baum3 = Baum1 + 2,
    Baum4 = Baum1 + 3,
    Busch = Baum1 + 4,
    Baum1Down = Baum1 + 5,
    Baum2Down = Baum1 + 6,
    Baum3Down = Baum1 + 7,
    Baum4Down = Baum1 + 8,
    BaumGross = Baum1 + 9,
    Feuer = Baum1 + 10,
    Wrack = Baum1 + 11,
    Wrack2 = Baum1 + 12,
    Feld = 38,
    Zelt = Feld + 1,
    Boot = Feld + 2,
    Rohr = Feld + 3,
    Sos = Feld + 4,
    Haus1 = Feld + 5,
    Haus2 = Feld + 6,
    Haus3 = Feld + 7,
    Feuerstelle = Feld + 8,
    CuPfeil = 47,
    CuRichtung = CuPfeil + 1,
    CuUhr = CuPfeil + 2,
    GuyLinks = 50,
    GuyOben = GuyLinks + 1,
    GuyRechts = GuyLinks + 2,
    GuyUnten = GuyLinks + 3,
    GuySuchen = GuyLinks + 4,
    GuyEssen = GuyLinks + 5,
    GuyTrinken = GuyLinks + 6,
    GuyFaellen = GuyLinks + 7,
    GuyWarten = GuyLinks + 8,
    GuyFeld = GuyLinks + 9,
    GuyBindenOben = GuyLinks + 10,
    GuyBindenUnten = GuyLinks + 11,
    GuySchlafen = GuyLinks + 12,
    GuySchlafZelt = GuyLinks + 13,
    GuyGehInZelt = GuyLinks + 14,
    GuyHinlegen = GuyLinks + 15,
    GuyAufstehen = GuyLinks + 16,
    GuyAngeln1Links = GuyLinks + 17,
    GuyAngeln1Oben = GuyLinks + 18,
    GuyAngeln1Rechts = GuyLinks + 19,
    GuyAngeln1Unten = GuyLinks + 20,
    GuyAngeln2Links = GuyLinks + 21,
    GuyAngeln2Oben = GuyLinks + 22,
    GuyAngeln2Rechts = GuyLinks + 23,
    GuyAngeln2Unten = GuyLinks + 24,
    GuyAngeln3Links = GuyLinks + 25,
    GuyAngeln3Oben = GuyLinks + 26,
    GuyAngeln3Rechts = GuyLinks + 27,
    GuyAngeln3Unten = GuyLinks + 28,
    GuySchlagen = GuyLinks + 29,
    GuyBootLinks = GuyLinks + 30,
    GuyBootOben = GuyLinks + 31,
    GuyBootRechts = GuyLinks + 32,
    GuyBootUnten = GuyLinks + 33,
    GuyBootAngeln1 = GuyLinks + 34,
    GuyBootAngeln2 = GuyLinks + 35,
    GuyBootAngeln3 = GuyLinks + 36,
    GuyTauchen1 = GuyLinks + 37,
    GuyTauchen2 = GuyLinks + 38,
    GuyTauchen3 = GuyLinks + 39,
    GuyHammer = GuyLinks + 40,
    GuyKlettern1 = GuyLinks + 41,
    GuyKlettern2 = GuyLinks + 42,
    GuyHammer2 = GuyLinks + 43,
    GuyGehInHaus = GuyLinks + 44,
    GuySchlafHaus = GuyLinks + 45,
    GuyGehausHaus = GuyLinks + 46,
    GuyAnzuenden = GuyLinks + 47,
    GuyAusschau = GuyLinks + 48,
    GuySchaufeln = GuyLinks + 49,
    GuySchiff = GuyLinks + 50,
    GuySchiffDown = GuyLinks + 51,
    GuySchwimmen = GuyLinks + 52,
    GuyTod = GuyLinks + 53,
    GuyBootTod = GuyLinks + 54,
    GuyBootWarten = GuyLinks + 55,
    GuySchleuder = GuyLinks + 56,
    ButtonGitter = 107,
    ButtonAnimation = ButtonGitter + 1,
    ButtonBeenden = ButtonGitter + 2,
    ButtonNew = ButtonGitter + 3,
    ButtonTagNeu = ButtonGitter + 4,
    ButtonSound = ButtonGitter + 5,
    ButtonAction = ButtonGitter + 6,
    ButtonBauen = ButtonGitter + 7,
    ButtonInventory = ButtonGitter + 8,
    ButtonWeiter = ButtonGitter + 9,
    ButtonStop = ButtonGitter + 10,
    ButtonAblegen = ButtonGitter + 11,
    ButtonSearch = 119,
    ButtonFood = ButtonSearch + 1,
    ButtonSleep = ButtonSearch + 2,
    ButtonTimber = ButtonSearch + 3,
    ButtonFish = ButtonSearch + 4,
    ButtonLight = ButtonSearch + 5,
    ButtonLook = ButtonSearch + 6,
    ButtonTreasureMap = ButtonSearch + 7,
    ButtonTreasure = ButtonSearch + 8,
    ButtonSlingshot = ButtonSearch + 9,
    ButtonTent = 129,
    ButtonField = ButtonTent + 1,
    ButtonBoat = ButtonTent + 2,
    ButtonPipe = ButtonTent + 3,
    ButtonSos = ButtonTent + 4,
    ButtonHouse1 = ButtonTent + 5,
    ButtonHouse2 = ButtonTent + 6,
    ButtonHouse3 = ButtonTent + 7,
    ButtonFireplace = ButtonTent + 8,
    ButtonQuestionMark = ButtonTent + 9,
    ButtonDestroy = ButtonTent + 10,
    Pillar1 = 140,
    Pillar2 = Pillar1 + 1,
    Pillar3 = Pillar1 + 2,
    ResourceBranch = 143,
    ResourceTrunk = ResourceBranch + 1,
    ResourceStone = ResourceBranch + 2,
    ResourceAxe = ResourceBranch + 3,
    ResourceLeaf = ResourceBranch + 4,
    ResourceHarrow = ResourceBranch + 5,
    ResourceVine = ResourceBranch + 6,
    ResourceFishingRod = ResourceBranch + 7,
    ResourceHammer = ResourceBranch + 8,
    ResourceTelescope = ResourceBranch + 9,
    ResourceMatchstick = ResourceBranch + 10,
    ResourceShovel = ResourceBranch + 11,
    ResourceMap = ResourceBranch + 12,
    ResourceSlingshot = ResourceBranch + 13,
    Roman1 = 157,
    Roman2 = Roman1 + 1,
    InventoryPaper = 159,
    Ring = InventoryPaper + 1,
    Cross = InventoryPaper + 2,
    Yes = InventoryPaper + 3,
    No = InventoryPaper + 4,
    Sun = InventoryPaper + 5,
    Programming = 165,
    DirkPlate = Programming + 1,
    Matthias = Programming + 2,
    Tobias = Programming + 3,
    Sigrid = Programming + 4,
    Sounds = Programming + 5,
    PathFinding = Programming + 6,
    John = Programming + 7,
    Heiko = Programming + 8,
    Gisela = Programming + 9,
    AdditionalHelp = Programming + 10,
    TestPlayers = Programming + 11,
    Black = Programming + 12,
    Music = Programming + 13,
    DpSoftware = Programming + 14,
    ImageCount = DpSoftware + 1, // Number Images
};

enum Textfields
{
    TXTTEXTFELD  = 0,
    TXTFPS       = 1,
    TXTTAGESZEIT = 2,
    TXTCHANCE    = 3,
    TXTPAPIER    = 4, // Must!!! remain as last entry
    TEXTANZ      = 5, // Number of text areas
};

// Resourcen
enum Resources
{
    WASSER     = 0,
    NAHRUNG    = 1,
    GESUNDHEIT = 2,
};

// Bilder
static const char Misc[]        = "MISC";
static const char Panel[]       = "PANEL";
static const char GuyAni[]      = "GUYANI";
static const char Animation[]   = "ANIMATION";
static const char Schrift1[]    = "SCHRIFT1";
static const char Schrift2[]    = "SCHRIFT2";
static const char TextFeld[]    = "TEXTFELD";
static const char Papier[]      = "PAPIER";
static const char Baum[]        = "BAUM";
static const char Cursorbmp[]   = "CURSORBMP";
static const char Buttons[]     = "BUTTONS";
static const char Inventarbmp[] = "INVENTARBMP";
static const char Bau[]         = "BAU";
static const char Credits[]     = "CREDITS";
static const char Logo[]        = "LOGO";
