//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Landscape.rc
//
#define TESTTEXT1                       1
#define GITTERAN                        2
#define GITTERAUS                       3
#define KEINEFUNKTION                   4
#define MEAKTIONAUF                     5
#define MEAKTIONZU                      6
#define BEGINNSUCHEN                    7
#define BEGINNFAELLEN                   8
#define SOSPAET                         9
#define BEGINNESSEN                     10
#define MEINVENTARAUF                   11
#define MEINVENTARZU                    12
#define FREI                            13
#define AST                             14
#define STEIN                           15
#define ROHASTGEFUNDEN                  16
#define ROHASTZUVIEL                    17
#define ROHSTEINGEFUNDEN                18
#define ROHSTEINZUVIEL                  19
#define NICHTSGEFUNDEN                  20
#define AXT                             21
#define KEINESSENTRINKEN                22
#define BAUEAXT                         23
#define STEINPLUSASTNICHTS              24
#define NICHTBASTELN                    25
#define ROHBLATTGEFUNDEN                26
#define ROHBLATTZUVIEL                  27
#define BLATT                           28
#define ROHSTAMMZUVIEL                  29
#define MEBAUENAUF                      30
#define MEBAUENZU                       31
#define BEGINNFELD                      32
#define GEGENDNICHT                     33
#define BAUEEGGE                        34
#define EGGE                            35
#define TAGENDE1                        36
#define GERETTET                        37
#define BEGINNZELT                      38
#define ROHSTOFFNICHT                   39
#define KEINBAUM                        40
#define WEITER                          41
#define STOP                            42
#define TAGENDE2                        43
#define BEGINNSCHLAFEN                  44
#define WIESETEXT                       45
#define MEERTEXT                        46
#define STRANDTEXT                      47
#define TREIBSANDTEXT                   48
#define FEUCHTEWIESETEXT                49
#define BAUMTEXT                        50
#define FELDTEXT                        51
#define ZELTTEXT                        52
#define BUSCHTEXT                       53
#define MIT                             54
#define LIANE                           55
#define ROHLIANEGEFUNDEN                56
#define ROHLIANEZUVIEL                  57
#define ANGEL                           58
#define BAUEANGEL                       59
#define BEGINNANGELN                    60
#define KEINWASSER                      61
#define BOOTTEXT                        62
#define BEGINNBOOT                      63
#define STAMM                           64
#define BEGINNABLEGEN                   65
#define TAGENDE3                        66
#define FLUSSTEXT                       67
#define BEGINNROHR                      68
#define ROHRTEXT                        69
#define BEGINNDESTROY                   70
#define KEINBAUWERK                     71
#define BEGINNSOS                       72
#define SOSTEXT                         73
#define BAUMZUGROSS                     74
#define BEGINNHAUS1                     75
#define HAUS1TEXT                       76
#define HAMMER                          77
#define BEGINNHAUS2                     78
#define HAUS2TEXT                       79
#define HAUS3TEXT                       80
#define BEGINNHAUS3                     81
#define TAGENDE4                        82
#define BAUMZUKLEIN                     83
#define NICHTOHNELEITER                 84
#define NICHTOHNEPLATTFORM              85
#define CHANCETEXT                      86
#define BAUMGROSSTEXT                   87
#define FEUERSTELLETEXT                 88
#define BEGINNFEUERSTELLE               89
#define FEUERTEXT                       90
#define BEGINNANZUENDEN                 91
#define KEINEFEUERST                    92
#define BEGINNAUSSCHAU                  93
#define FERNROHR                        94
#define BEGINNSCHATZKARTE               95
#define SCHAUFEL                        96
#define STREICHHOLZ                     97
#define BEGINNSCHATZ                    98
#define SCHATZGEFUNDEN                  99
#define KEINSCHATZ                      100
#define WRACKTEXT                       101
#define FERNROHRGEFUNDEN                102
#define INTROTEXT                       103
#define NICHTSGEFUNDEN2                 104
#define KARTE                           105
#define KARTEGEFUNDEN                   106
#define ANIMATIONAUS                    107
#define ANIMATIONAN                     108
#define ASTPLUSLIANENICHTS              109
#define SCHLEUDER                       110
#define STEINPLUSLIANENICHTS            111
#define BAUESCHLEUDER                   112
#define KEINVOGEL                       113
#define BEGINNSCHLEUDER                 114
#define NICHTAUFWASSERSCHLAFEN          115
#define WELLENZUHOCH                    116
#define IDI_MAIN_ICON                   117
#define GRABENBEDINGUNGEN               117
#define FELDBEDINGUNGEN                 118
#define ZELTBEDINGUNGEN                 119
#define BOOTBEDINGUNGEN                 120
#define ROHRBEDINGUNGEN                 121
#define SOSBEDINGUNGEN                  122
#define FEUERSTELLENBEDINGUNGEN         123
#define BOOTHILFE                       124
#define FELDHILFE                       125
#define FEUERSTELLEHILFE                126
#define HAUS3HILFE                      127
#define ROHRHILFE                       128
#define SOSHILFE                        129
#define ZELTHILFE                       130
#define SPIELVERLASSEN                  131
#define BEENDEN                         132
#define NEUBEGINNEN                     133
#define NEU                             134
#define TAGNEU                          135
#define TOD                             136
#define TAGENDE5                        137
#define TAGNEU2                         138
#define SOUNDAN                         139
#define SOUNDAUS                        140
#define KEINSOUND                       141

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
