const char *GetLanguageString(const unsigned index) { static const char *strings[] = { "Since this file is used 1-indexed, this line is not used.", "Dies ist ein Test. /a Dies ist ein Test. Dies ist ein Test. Dies ist ein Test. Dies ist ein Test. Dies ist ein Test. /z /z Dies ist ein Test. Dies ist ein Test. Dies ist ein Test. Dies ist ein Test. Dies ist ein Test. Dies ist ein Test. Dies ist ein Test. Dies ist ein Test. Dies ist ein Test.",
        "Gitternetz anschalten",
        "Gitternetz ausschalten",
        "Diese Funktion ist leider noch nicht integriert. Warten Sie bitte eine spaetere Version von Schiffbruch ab. Dann wird Ihnen der gesamte Funktionsumfang zur Verfuegung stehen.",
        "Oeffnet das Aktionsmenue",
        "Schliesst das Aktionsmenue",
        "Durchsuche die Umgebung",
        "Baum faellen",
        "Schon so spaet?",
        "Essen und trinken",
        "Oeffnet das Inventar",
        "Schliesst das Inventar",
        ".",
        "Ast",
        "Stein",
        "Nach ewigem Suchen in der prallen Sonne habe ich einen Ast gefunden. Genau das, was mir noch gefehlt hat. Die Suche hat sich gelohnt.",
        "Nachdem ich mich muehsam durch die Gegend gewuehlt habe, finde ich einen wunderschoenen Ast. Allerdings schleppe ich schon so viele Aeste mit mir herum, dass ich ihn wieder wegwerfe.",
        "In der tropischen Hitze habe ich mir in den letzen Minuten die naehere Umgebung genauer angeschaut. Besonders aufgefallen sind mir diese wunderschoenen Steine. Diese drei kann ich gut gebrauchen und packe sie ein.",
        "Jaa, ich habe etwas gefunden!! Einen Stein!! Mir reichen allerdings die, die ich schon in der Tasche habe, und werfe ihn deshalb bis ins Meer (Hoffentlich habe ich nicht das mich rettende Schiff getroffen!).",
        "Selbst nachdem ich die Gegend sehr genau unter die Lupe genommen habe, habe ich absolut nichts gefunden. ",
        "Axt",
        "Hier gibt es weder etwas zu essen noch zu trinken.",
        "Mit viel Geschick habe ich einen Stein mit einem Ast verbunden und eine Axt erhalten. Damit bin ich nun in der Lage, Holz zu bearbeiten, zum Beispiel Baeume faellen. /z Ich glaube, ich koennte mir noch etwas aus einem Ast und einem Stein bauen.",
        "Leider gibt es nichts mehr, was ich mit einem Stein und einem Stock bauen kann.",
        "Aus diesen beiden Sachen kann ich mir nichts Sinnvolles bauen. Vielleicht sollte ich zwei andere Dinge probieren?",
        "Mmh, das ist aber ein grosses Blatt. Das kann ich sicher noch gebrauchen, ich werde es vorsichtshalber mitnehmen. Wer weiss, ob ich noch einmal so etwas Besonderes finde.",
        "Schon wieder so ein seltenes Blatt. Sie scheinen doch relativ haeufig zu sein, deshalb werde ich es nicht mitnehmen.",
        "Blatt",
        "Noch mehr Baumstaemme brauche ich im Moment nicht. ",
        "Oeffnet das Baumenue",
        "Schliesst das Baumenue",
        "Feld anlegen",
        "Diese Gegend ist leider nicht geeignet.",
        "Nachdem ich einen laenglichen Stein an einen Ast gebunden habe, sieht das ganze wie eine Egge aus. Damit sollte es mir moeglich sein, ein Feld anzulegen, so dass ich nicht mehr nur auf diese laestigen Buesche angewiesen bin.",
        "Egge",
        "Tag /a ist nun zu Ende. Leider habe ich es nicht mehr bis zu einer angenehmen Schlafstelle geschafft, deshalb muss ich heute nacht unter freien Himmel schlafen. Die wilden Tiere lassen mir keine Ruhe, deshalb sinkt meine Gesundheit auf /b %. Meine Chance gerettet zu werden betraegt /c %.",
        "Endlich ein Schiff!! Dank meiner intensiven Bemuehungen wurde ich entdeckt und nun ankert das Schiff vor der Insel. Soll ich diese trostlose Insel verlassen? /d ",
        "Zelt bauen",
        "Ich habe leider nicht genug Rohstoffe, um den Bau fortzusetzen.",
        "Hier steht leider kein Baum.",
        "Vorgang fortsetzen",
        "Vorgang unterbrechen",
        "Tag /a ist nun zu Ende. Zum Glueck bin ich rechtzeitig zu meinem Zelt gekommen, so lassen mich wenigstens die Fledermaeuse in Ruhe. Allerdings beissen mich wilde Tiere in meine Fuesse, deshalb sinkt meine Gesundheit auf /b %. Meine Chance gerettet zu werden betraegt /c %.",
        "1 Stunde schlafen",
        "Wiese",
        "Meer",
        "Strand",
        "Treibsand",
        "feuchte Wiese",
        "Baum",
        "Feld",
        "Zelt",
        "Busch",
        "mit",
        "Liane ",
        "Mit sehr viel Muehe habe ich es geschafft, eine Liane vom Baum abzureissen. Mit Lianen kann man sehr viel anstellen, deshalb werde ich sie die naechste Zeit mit mir herumschleppen.",
        "So nuetzlich sind Lianen dann doch wieder nicht, dass ich so viele davon mit mir herumtragen muss.",
        "Angel",
        "Dieser duenne, biegsame Ast und diese Liane lassen sich vorzueglich zu einer Angel verbinden. Endlich muss ich nicht mehr vegetarisch leben und kann mir ein paar fette Forellen fischen.",
        "Angeln",
        "Wo soll ich denn hier angeln?",
        "Einbaum",
        "Einbaum bauen",
        "Baumstamm",
        "An- und Ablegen",
        "Tag /a ist nun zu Ende. Es ist stockdunkel, ich treibe ab und werde wohl sterben. Das wird mir eine Lehre sein. ",
        "Fluss",
        "Bewaesserungsanlage bauen",
        "Bewaesserungsrohr",
        "Bauwerk abreissen",
        "Hier ist leider kein Bauwerk, das ich abreissen kann.",
        "S.O.S. schreiben",
        "S.O.S.",
        "Der ist mir eine Nummer zu gross.",
        "Leiter fuer Baumhaus bauen",
        "Baum und Leiter",
        "Hammer",
        "Plattform fuer Baumhaus bauen",
        "Baum und Plattform",
        "Baum und Baumhaus",
        "Baumhaus bauen",
        "Tag /a ist nun zu Ende. Bin ich froh, dass ich mir dieses schoene Baumhaus gebaut habe. So lassen mich die wilden Tiere in Frieden. Ich schlafe ausgezeichnet und meine Gesundheit steigt auf /b %. Meine Chance gerettet zu werden betraegt /c %.",
        "Dieser Baum ist eine Nummer zu klein.",
        "Ohne Leiter kann ich keine Plattform bauen.",
        "Das Baumhaus kann ich nur auf einer Plattform bauen.",
        "Meine Chance heute gerettet zu werden",
        "grossem Baum",
        "Feuerstelle",
        "Holz fuer Feuerstelle aufstapeln",
        "Signalfeuer",
        "Feuerstelle anzuenden",
        "Ich kann nur Feuerstellen anzuenden",
        "Nach Rettung Ausschau halten",
        "Fernrohr",
        "Schatzkarte anschauen",
        "Schaufel",
        "Streichhoelzer",
        "Nach Schatz graben",
        "Hurra!! Ich habe einen alten Piratenschatz gefunden. Mit Hoffnung auf einen grossartigen Schatz oeffnete ich die alte modrige Kiste und entdeckte ... nur eine Streichholzschachtel. Was solls, ich kann mir hier eh nichts kaufen.",
        "Obwohl ich die ganze Gegend hier umgegraben habe, habe ich keinen Schatz gefunden. Vielleicht sollte ich mir erst eine Schatzkarte anschauen.",
        "Schiffswrack",
        "Ich habe das gesamte Wrack abgesucht.Als ich in die Kapitaenskajute getaucht bin, habe ich mein altes Fernrohr gefunden. Damit kann ich nach Schiffen Ausschau halten und meine Chance, gerettet zu werden, steigt. /z Auf dem Weg nach draussen entdeckte ich noch den Hammer und einige Naegel vom Schiffszimmermann. Damit kann ich mir eine stabilere Behausung bauen.",
        "Jetzt habe ich den Schlamassel: Gestrandet auf einer einsamen Insel mitten im Pazifik. Ich sollte mich schnellstens nach Suesswasser und Nahrung umsehen. Vielleicht kann ich mir auch ein paar Werkzeuge bauen.",
        "Ich habe den ganzen Grund abgesucht, aber nichts von Interesse gefunden.",
        "Schatzkarte",
        "Ich tauchte durch das uralte Piratenschiff, allerdings ohne etwas zu finden, bis ich ploetzlich das Skelett des Kapitains fand. In der Hand hielt er noch eine erstaunlich gut erhaltene Schatzkarte. Nachdem ich sie an mich genommen hatte, nahm ich mir noch eine Schaufel mit. Jetzt kann ich mir die Zeit mit einer Schatzsuche vertreiben. ",
        "Wasseranimationen ausschalten",
        "Wasseranimationen anschalten",
        "Mehr kann ich mir auch mit einer Liane und einem Ast nicht bauen.",
        "Steinschleuder",
        "Mir faellt nichts mehr ein, was ich mir aus einer Liane und einem Stein bauen k�nnte.",
        "Ich knotete eine Schlaufe in die Liane und jetzt kann man sie als Steinschleuder missbrauchen. Einfach noch den Stein in die Schlaufe gelegt und ich kann auf Jagd gehen. Da es am Tag auf dieser Insel nur Voegel zu geben scheint, sollte ich mich darauf beschraenken, diese Tiere von den Baeumen zu schiessen.",
        "Hier sind keine Voegel.",
        "Auf Vogeljagd gehen",
        "In diesem kleinen Boot ist es zum Schlafen zu gefaehrlich.",
        "Die Wellen sind zu hoch, um etwas zu sehen.",
        "Ich kann nur auf flachen und freien Gegenden nach einem Schatz graben.",
        "Felder kann ich nur auf flachen, feuchten und freien Wiesen anlegen.",
        "Zelte kann ich nur auf einer flachen und freien Gegend bauen.",
        "Boote kann ich nur auf einem freien Strandabschnitt bauen.",
        "Rohre kann ich nur auf flachen und freien Gegenden bauen.",
        "SOS kann ich nur auf flachen und freien Gegenden schreiben.",
        "Feuerstellen kann ich nur in flachen und freien Landschaften anlegen.",
        "Ich habe nun mein erstes Boot gebaut. (Zum An- und Ablegen auf den 'Anker-Knopf' klicken.) Anlegen kann ich nur, wenn auf dem Strand nichts im Weg ist. Auch sollte ich immer die Zeit im Auge haben, da ich eine Nacht auf hoher See nicht ueberleben wuerde.",
        "Mein erstes Feld ist fertig. Das Getreide wird von ganz allein wachsen und, wenn es schoen gelb ist, kann ich es essen. ",
        "Jetzt habe ich einen grossen Haufen Holz aufgebaut. Womit kann ihn anzuenden? Das Feuer wuerde eine Weile brennen und meine Chance erhoehen, gerettet zu werden. Je hoeher die Feuerstelle liegt, desto besser.",
        "Meine Baumhaus ist endlich fertig. Dort kann ich jederzeit ein Schlaefchen machen und mich erholen. Wenn ich dort uebernachten will, sollte ich puenktlich um 18.00 Uhr, wenn es dunkel wird, in unmittelbarer Naehe sein.",
        "Jetzt besitze ich eine eigene Bewaesserungsanlage. Sie wird sich mit Wasser fuellen, wenn ich sie in der Naehe eines Flusses gebaut habe. Damit werden die anliegenden Wiesen befeuchtet, so dass ich auch dort Felder anlegen kann. Diese gehen natuerlich auch wieder ein, wenn ich das Rohr abreisse.",
        "So, jetzt muessten mich vorbeifliegende Flugzeuge bemerken und Hilfe schicken. Auf dem Strand ist das SOS besonders gut zu lesen.",
        "Endlich habe ich ein Dach ueber dem Kopf. Dort kann ich jederzeit ein Nickerchen machen. Wenn ich es auch in der Nacht benutzen will, muss ich mich, wenn es dunkel wird (18.00 Uhr), in der Naehe befinden.",
        "Willst du das Spiel wirklich verlassen? /z (Der Spielstand wird automatisch gespeichert) /d ",
        "Spiel beenden",
        "Willst du das Spiel neu starten? /d ",
        "Spiel neu starten",
        "Willst du den Tag noch einmal neu beginnen? /d ",
        "Ich fuehle mich ploetzlich ganz seltsam. Ich spuere, dass ich sterbe...",
        "Tag /a ist nun zu Ende. Ich fuehle mich nicht besonders gut und werde die Nacht wohl nicht ueberleben. ",
        "Tag neu starten",
        "Sound anstellen",
        "Sound austellen",
        "Leider kein Sound"
    };
    if (index >= sizeof strings) {
        return "????";
    }
    return strings[index];
}
