#define TESTTEXT1                       1
#define GITTERAN                        2
#define GITTERAUS                       3
#define KEINEFUNKTION                   4
#define MEAKTIONAUF                     5
#define MEAKTIONZU                      6
#define STRING_BEGIN_SEARCH                    7
#define BEGINNFAELLEN                   8
#define SOSPAET                         9
#define BEGINNESSEN                     10
#define MEINVENTARAUF                   11
#define MEINVENTARZU                    12
#define FREI                            13
#define AST                             14
#define STEIN                           15
#define ROHASTGEFUNDEN                  16
#define ROHASTZUVIEL                    17
#define ROHSTEINGEFUNDEN                18
#define ROHSTEINZUVIEL                  19
#define NICHTSGEFUNDEN                  20
#define STRING_AXE                             21
#define STRING_NOTHING_EAT_DRINK                22
#define STRING_BUILD_AXE                         23
#define STRING_STONE_BRANCH_NOTHING_ELSE              24
#define STRING_CANT_BUILD                    25
#define STRING_LEAF_FOUND                26
#define STRING_ALREADY_HAVE_LEAF                  27
#define STRING_LEAF                           28
#define ROHSTAMMZUVIEL                  29
#define MEBAUENAUF                      30
#define MEBAUENZU                       31
#define BEGINNFELD                      32
#define GEGENDNICHT                     33
#define BAUEEGGE                        34
#define EGGE                            35
#define TAGENDE1                        36
#define GERETTET                        37
#define BEGINNZELT                      38
#define ROHSTOFFNICHT                   39
#define KEINBAUM                        40
#define WEITER                          41
#define STOP                            42
#define TAGENDE2                        43
#define STRING_BEGIN_SLEEP                  44
#define WIESETEXT                       45
#define STRING_SEA                        46
#define STRING_BEACH                      47
#define STRING_QUICKSAND                   48
#define STRING_DAMP_PLAIN                49
#define STRING_TREE                        50
#define STRING_FIELD                        51
#define STRING_TENT                        52
#define STRING_BUSH                       53
#define STRING_WITH                             54
#define STRING_LIANA                           55
#define STRING_LIANA_FOUND                56
#define STRING_LIANA_FULL                  57
#define ANGEL                           58
#define BAUEANGEL                       59
#define STRING_BEGIN_FISHING                    60
#define STRING_NO_FISHINGWATER                      61
#define BOOTTEXT                        62
#define BEGINNBOOT                      63
#define STAMM                           64
#define BEGINNABLEGEN                   65
#define TAGENDE3                        66
#define FLUSSTEXT                       67
#define BEGINNROHR                      68
#define ROHRTEXT                        69
#define STRING_BEGIN_DESTROY                   70
#define STRING_NOTHING_TO_DESTROY                     71
#define STRINGBEGIN_WRITE_SOS                       72
#define SOSTEXT                         73
#define BAUMZUGROSS                     74
#define BEGINNHAUS1                     75
#define HAUS1TEXT                       76
#define HAMMERTEXT                      77
#define BEGINNHAUS2                     78
#define STRING_TREE_AND_PLATFORM                       79
#define HAUS3TEXT                       80
#define STRING_BUILD_TREEHOUSE                     81
#define TAGENDE4                        82
#define BAUMZUKLEIN                     83
#define NICHTOHNELEITER                 84
#define NICHTOHNEPLATTFORM              85
#define CHANCETEXT                      86
#define STRING_BIG_TREE                   87
#define STRING_BONFIRE                 88
#define STRING_BEGIN_BONFIRE               89
#define STRING_SMOKE_SIGNAL                       90
#define STRING_LIGHT_BONFIRE                 91
#define STRING_ONLY_LIGHT_BONFIRE                    92
#define STRING_BEGIN_LOOK_OUT                  93
#define STRING_TELESCOPE                        94
#define STRING_BEGIN_TREASUREMAP               95
#define STRING_SHOVEL                        96
#define STRING_MATCHES                     97
#define STRING_BEGIN_TREASUREDIG                    98
#define SCHATZGEFUNDEN                  99
#define KEINSCHATZ                      100
#define WRACKTEXT                       101
#define STRING_TELESCOPE_FOUND                102
#define INTROTEXT                       103
#define NICHTSGEFUNDEN2                 104
#define STRING_MAP                           105
#define KARTEGEFUNDEN                   106
#define ANIMATIONAUS                    107
#define ANIMATIONAN                     108
#define ASTPLUSLIANENICHTS              109
#define STRING_SLINGSHOT                       110
#define STEINPLUSLIANENICHTS            111
#define BAUESCHLEUDER                   112
#define KEINVOGEL                       113
#define BEGINNSCHLEUDER                 114
#define NICHTAUFWASSERSCHLAFEN          115
#define WELLENZUHOCH                    116
#define IDI_MAIN_ICON                   117
#define GRABENBEDINGUNGEN               117
#define FELDBEDINGUNGEN                 118
#define ZELTBEDINGUNGEN                 119
#define BOOTBEDINGUNGEN                 120
#define ROHRBEDINGUNGEN                 121
#define SOSBEDINGUNGEN                  122
#define FEUERSTELLENBEDINGUNGEN         123
#define BOOTHILFE                       124
#define FELDHILFE                       125
#define FEUERSTELLEHILFE                126
#define HAUS3HILFE                      127
#define ROHRHILFE                       128
#define SOSHILFE                        129
#define ZELTHILFE                       130
#define SPIELVERLASSEN                  131
#define BEENDEN                         132
#define NEUBEGINNEN                     133
#define NEU                             134
#define TAGNEU                          135
#define TOD                             136
#define TAGENDE5                        137
#define TAGNEU2                         138
#define SOUNDAN                         139
#define SOUNDAUS                        140
#define KEINSOUND                       141

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
